server:
  port: 9090

spring:
  security:
    user:
      name: ${java15grup2proje_security_name}
      password: ${java15grup2proje_security_password}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${java15grup2proje_postgre_url}
    username: ${java15grup2proje_postgre_username}
    password: ${java15grup2proje_postgre_password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${java15grup2proje_mail_address}
    password: ${java15grup2proje_mail_app_password}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
logging:
  level:
    root: info
    com.muhammet.java15_x: trace
  logback:
    rollingpolicy:
      max-file-size: 2MB
  file:
    path: ./log

java15grup2proje:
  jwt:
    secret-key: ${java15grup2proje_jwt_secretkey}
    issuer: ${java15grup2proje_jwt_issuer}
  refreshtoken:
    duration: ${java15grup2proje_refreshtoken_duration}