server:
  port: 9090

spring:
  security:
    user:
      name: emirhan
      password: 1234567a
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${java15grup2proje_postgre_url}
    username: ${java15grup2proje_postgre_username}
    password: ${java15grup2proje_postgre_password}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    root: info
    com.muhammet.java15_x: trace
  logback:
    rollingpolicy:
      max-file-size: 2MB
  file:
    path: ./log

java15grup2proje:
  jwt:
    secret-key: aaa
    issuer: asfasfasfasfas