server:
  port: 9090

spring:
  security:
    user:
      name: emirhan
      password: 1234567a
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/java15grup2proje
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  file:
    name: proje.log
  level:
    root: info
    com.muhammet.java15_x: trace
  logback:
    rollingpolicy:
      max-file-size: 2MB


java15:
  jwt:
    secret-key: aaa
    issuer: asfasfasfasfas